version: '3'

services:
  db:
    image: postgres:14.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  redis:
    image: "redis:alpine"
  web:
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/climada_calcapi
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: on-failure
    env_file:
      - .env
  celery:
    build: .
    command: celery -A calc_api worker -l info
    volumes:
      - .:/climada_calc
    depends_on:
      - db
      - redis
  celery_flower:
    build: .
    command: celery -A calc_api flower
    volumes:
      - .:/climada_calc
    depends_on:
      - db
      - redis
    restart: on-failure

volumes:
  postgres_data:

