# Generated by Django 4.0 on 2022-04-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cobenefit',
            fields=[
                ('value', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileCache',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.TextField(unique=True)),
                ('function', models.TextField()),
                ('args', models.TextField(null=True)),
                ('kargs', models.TextField(null=True)),
                ('path', models.TextField(null=True)),
                ('locked', models.BooleanField()),
            ],
            options={
                'db_table': 'file_cache',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.TextField(db_index=True, primary_key=True, serialize=False)),
                ('location', models.TextField()),
                ('status', models.TextField()),
                ('request', models.JSONField()),
                ('submitted_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField()),
                ('runtime', models.FloatField(null=True)),
                ('response', models.JSONField(null=True)),
                ('response_uri', models.URLField(null=True)),
                ('code', models.IntegerField(null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(null=True)),
                ('hazard_type', models.TextField()),
                ('exposure_type', models.TextField(null=True)),
                ('cost_type', models.TextField(default='whole_project')),
                ('cost', models.FloatField()),
                ('annual_upkeep', models.FloatField(default=0)),
                ('priority', models.TextField(default='even_coverage')),
                ('percentage_coverage', models.FloatField(default=100)),
                ('percentage_effectiveness', models.FloatField(default=100)),
                ('is_coastal', models.BooleanField(default=False)),
                ('max_distance_from_coast', models.FloatField(null=True)),
                ('hazard_cutoff', models.FloatField(null=True)),
                ('return_period_cutoff', models.FloatField(null=True)),
                ('hazard_change_multiplier', models.FloatField(null=True)),
                ('hazard_change_constant', models.FloatField(null=True)),
                ('units_currency', models.TextField()),
                ('units_hazard', models.TextField()),
                ('units_distance', models.TextField()),
                ('user_generated', models.BooleanField()),
                ('cobenefits', models.ManyToManyField(to='calc_api.Cobenefit')),
            ],
        ),
    ]
