# Generated by Django 4.0 on 2022-05-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exposures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('value', models.FloatField()),
                ('reg_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField()),
                ('event_id', models.FloatField()),
                ('event_name', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ImpactRP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('haz_uuid', models.UUIDField()),
                ('exp_uuid', models.UUIDField()),
                ('impf_uuid', models.UUIDField(blank=True)),
                ('scaling', models.FloatField(blank=True)),
                ('rp', models.CharField(max_length=4)),
                ('value', models.FloatField()),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('admin1_code', models.CharField(blank=True)),
                ('admin2_code', models.CharField(blank=True)),
                ('poly', models.CharField(blank=True)),
                ('lat', models.FloatField(blank=True)),
                ('lon', models.FloatField(blank=True)),
            ],
        ),
    ]
