# Generated by Django 4.0 on 2022-10-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_api', '0006_ssp_gdp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblog',
            name='func',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='joblog',
            name='job_hash',
            field=models.UUIDField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='joblog',
            name='result',
            field=models.JSONField(null=True),
        ),
    ]
