# Generated by Django 4.0 on 2022-10-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_api', '0007_alter_joblog_func_alter_joblog_job_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblog',
            name='job_hash',
            field=models.CharField(db_index=True, max_length=36, primary_key=True, serialize=False),
        ),
    ]
